version: '{build}'
pull_requests:
  do_not_increment_build_number: true
max_jobs: 1
image: Visual Studio 2019
branches:
  only:
  - master

init:
- git config --global user.email "d.k.ivanov@live.com"
- git config --global user.name "Dmitriy Ivanov"
- git config --global core.safecrlf false

build_script:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- git --version
- choco --version
- ps: |
    "Build info"
    '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
    '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
    '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')
